version: '3.8'

services:
  go_app:
    image: "ubuntu:22.04"
    command: ""
    volumes:
      - ../:/app
    env_file:
      - './dev.env'
    ports:
      - "8000:8000"
    depends_on:
      - "db"
  db:
    image: postgres:13
    env_file:
      - './dev.env'

